name: GitHub-Hosted Runner
on: 
    workflow_dispatch:
jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: OS Name, Runner's Hostname and Current User Running the job
              run: |
                echo "------ UBUNTU ------"
                echo "OS Name - ${{ runner.os }}"
                echo "Runner's HostName - ${{ runner.name }}"
                echo "Current User - $(whoami)"

            - name: Checking Versions of docker, python, node and git
              run: |
                echo "Docker: $(docker --version)"
                echo "Pyhton: $(python3 --version)"
                echo "Node: $(node --version)"
                echo "Git: $(git --version)"


    window:
        runs-on: windows-latest
        steps:
            - name: OS Name, Runner's Hostname and Current User Running the job
              shell: pwsh
              run: |
                echo "------ WINDOWS ------"
                echo "OS Name - ${{ runner.os }}"
                echo "Runner's HostName - ${{ runner.name }}"
                echo "Current User - $env:USERNAME"

    mac:
        runs-on: macos-latest
        steps:
            - name: OS Name, Runner's Hostname and Current User Running the job
              run: |
                echo "------ MAC-OS ------"
                echo "OS Name - ${{ runner.os }}"
                echo "Runner's HostName - ${{ runner.name }}"
                echo "Current User - $(whoami)"
