name: Secrets in GitHub Actions
on:
    workflow_dispatch:

jobs:
    read-and-print-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Reading the secret
              env:
                MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
              run: |
                echo "The secret is set: true"

            - name: Trying to print the actual secret message.
              run: |
                echo "Secret is - ${{ secrets.MY_SECRET_MESSAGE }}"
                
