name: Paths Filter

on:
    # push:
    #     paths:
    #       - 'src/**'
    #       - 'app/**'
    workflow_dispatch:

jobs:
    paths:
        runs-on: ubuntu-latest
        steps:
            - name: Intro
              run: echo "This workflow is triggered by 'paths:'"